server:
  port: 8082
  error:
    include-stacktrace: on_param
    include-binding-errors: always
    include-exception: false
    include-message: always

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # a day
  refresh-token:
    expiration: 604800000 # 7 days
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/workcontract?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: rootroot
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: luka.mugosa@amplitudo.me
    password: fdrxwokuotcwthau
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: true

logging:
  level:
    liquibase: INFO